version: "3.8"

services:
  nginx-sanryuu:
    container_name: nginx-sanryuu
    image: nginx:latest
    ports:
      - protocol: tcp
        published: 80
        target: 80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/ssl