version: "3.8"

services:
  nginx-sanryuu:
    container_name: nginx-sanryuu
    image: nginx:latest
    ports:
      - protocol: tcp
        published: 8080
        target: 80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/sangwolves.my.id.pem:/etc/ssl
      - ./ssl/sangwolves.my.id.key:/etc/ssl